name: Integration Tests

on: [push]

jobs:
  build-tcpb-cpp:
    runs-on: self-hosted
    container:
      image: henryw7/terachem_compilation_enviroment:0.0.1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run configure script
        run: ./configure intel
      - name: Run make
        run: make -j12 install
      - name: List files
        run: ls -l
  build-terachem:
    needs: build-tcpb-cpp
    runs-on: self-hosted
    container:
      image: henryw7/terachem_compilation_enviroment:0.0.1
    steps:
      -	name: List files
       	run: ls	-l
