name: Integration Tests

on: [push]

jobs:
  build-tcpb-cpp:
    runs-on: self-hosted
    container:
      image: henryw7/terachem_compilation_enviroment:0.0.1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run configure script
        run: ./configure intel
      - name: Run make
        run: make -j12 install
      - name: Install pyTCPB
        run: cd pytcpb && python setup.py build
  build-terachem:
    runs-on: self-hosted
    needs: build-tcpb-cpp
    container:
      image: henryw7/terachem_compilation_enviroment:0.0.1
    steps:
      - name: Clone TeraChem repo
        run: git clone https://imd-mtz:${{ secrets.IMD_MTZ_PAT }}@github.com/mtzgroup/terachem.git terachem
      - name: Configure TeraChem
        run: |
          cd terachem
          HOSTNAME=fire-fake ./configure
          cd ..
      - name: Compile TeraChem
        run: |
          cd terachem
          make -j32
          cd ..
      - name: Look for TeraChem
        run: |
          source terachem/build/terachem.sh
          which terachem
  run-test-suite:
    runs-on: self-hosted
    needs: build-terachem
    container:
      image: henryw7/terachem_compilation_enviroment:0.0.1
    steps:
      - name: Clone TeraChem Test Suite repo
        run: git clone https://imd-mtz:${{ secrets.IMD_MTZ_PAT }}@github.com/mtzgroup/terachem-test-suite.git terachem-test-suite
      - name: Change branch
        run: |
          cd terachem-test-suite
          git checkout vwdc
          cd ..
      - name: Run TCPB-cpp tests
        run: |
          source terachem/build/terachem.sh
          export LD_LIBRARY_PATH=$(pwd)/lib:$LD_LIBRARY_PATH
          export PYTHONPATH=$(pwd)/pytcpb/build/lib:$PYTHONPATH
          cd terachem-test-suite
          python test.py -c TCPB-cpp -g 0
          cd ..
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            terachem-test-suite/run.log
            terachem-test-suite/summary.out
            terachem-test-suite/summary.err
          if-no-files-found: error
