name: Integration Tests

on: [push]

jobs:
  build-tcpb-cpp:
    runs-on: self-hosted
    container:
      image: henryw7/terachem_compilation_enviroment:0.0.1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run configure script
        run: ./configure intel
      - name: Run make
        run: make -j12 install
      - name: Install pyTCPB
        run: make pytcpb
  build-terachem:
    runs-on: self-hosted
    needs: build-tcpb-cpp
    container:
      image: henryw7/terachem_compilation_enviroment:0.0.1
    steps:
      - name: Clone TeraChem repo
        run: git clone https://imd-mtz:${{ secrets.IMD_MTZ_PAT }}@github.com/mtzgroup/terachem.git terachem
      - name: Configure TeraChem
        run: |
          cd terachem
          HOSTNAME=fire-fake ./configure
          cd ..
      - name: Compile TeraChem
        run: |
          cd terachem
          make -j32
          cd ..
      - name: Set enviromental variables
        run: |
          export TeraChem=$(pwd)/terachem/build
          export PATH=$TeraChem/bin:$PATH
          export LD_LIBRARY_PATH=$TeraChem/lib:$LD_LIBRARY_PATH
          echo $PATH
          which terachem
      - run: which terachem
