name: Integration Tests

on: [push]

jobs:
  build-tcpb-cpp:
    runs-on: self-hosted
    container:
      image: henryw7/terachem_compilation_enviroment:0.0.1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run configure script
        run: ./configure --prefix=/usr/local intel
      - name: Run make
        run: make -j12 install
      - name: Install pyTCPB
        run: make pytcpb
  check-pytcpb:
    runs-on: self-hosted
    needs: build-tcpb-cpp
    container:
      image: henryw7/terachem_compilation_enviroment:0.0.1
    steps:
      - name: List libs
        run: ls -l /root/miniconda2/lib/python2.7/site-packages
      - name: Check
        run: |
          echo "import pytcpb" > eita.py
          echo "print(pytcpb.__file__)" >> eita.py
          cat eita.py
          python eita.py
  build-terachem:
    runs-on: self-hosted
    needs: check-pytcpb
    container:
      image: henryw7/terachem_compilation_enviroment:0.0.1
    steps:
      - name: Clone TeraChem repo
        run: git clone https://imd-mtz:${{ secrets.IMD_MTZ_PAT }}@github.com/mtzgroup/terachem.git terachem
      - name: Configure TeraChem
        run: |
          cd terachem
          HOSTNAME=fire-fake ./configure
          cd ..
      - name: Compile TeraChem
        run: |
          cd terachem
          make -j32
          cd ..
      - name: Look for TeraChem
        run: |
          source terachem/build/terachem.sh
          which terachem
  run-test-suite:
    runs-on: self-hosted
    needs: build-terachem
    container:
      image: henryw7/terachem_compilation_enviroment:0.0.1
    steps:
      - name: Clone TeraChem Test Suite repo
        run: git clone https://imd-mtz:${{ secrets.IMD_MTZ_PAT }}@github.com/mtzgroup/terachem-test-suite.git terachem-test-suite
      - name: Change branch
        run: |
          cd terachem-test-suite
          git checkout vwdc
          cd ..
      - name: Run TCPB-cpp tests
        run: |
          source terachem/build/terachem.sh
          cd terachem-test-suite
          python test.py -c QMMM TCPB-cpp -g 0
          cd ..
      - name: Print run.log
        if: always()
        run: |
          cat terachem-test-suite/run.log
          ls -l
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            run.log
            summary.out
            summary.err
          if-no-files-found: error
