name: Integration Tests

on:
  push:
    branches: master
    paths-ignore:
      - README.md
  pull_request:
    branches: master
    paths-ignore:
      - README.md

jobs:
  build-tcpb-cpp:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run configure script
        run: ./configure intel
      - name: Run make
        run: make -j12 install
