name: Integration Tests

on:
  push:
    branches: master
    paths-ignore:
      - README.md
  pull_request:
    branches: master
    paths-ignore:
      - README.md

jobs:
  build-tcpb-cpp:
    runs-on: self-hosted
    container:
      image: vwcruzeiro/terachem_environment:latest
      env:
        CUDA_VISIBLE_DEVICES: ${{ env.CUDA_VISIBLE_DEVICES }}
    steps:
      - name: Name of the runner executing this job
        run: echo ${{ runner.name }}
      - name: Print CUDA_VISIBLE_DEVICES, as seen inside the Docker container
        run: echo $CUDA_VISIBLE_DEVICES
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run configure script
        run: ./configure intel
      - name: Run make
        run: make -j16 install
      - name: Install pyTCPB
        run: cd pytcpb && python setup.py build
  build-terachem:
    runs-on: self-hosted
    needs: build-tcpb-cpp
    container:
      image: vwcruzeiro/terachem_environment:latest
      env:
        CUDA_VISIBLE_DEVICES: ${{ env.CUDA_VISIBLE_DEVICES }}
    steps:
      - name: Name of the runner executing this job 
        run: echo ${{ runner.name }}
      - name: Print CUDA_VISIBLE_DEVICES, as seen inside the Docker container
        run: echo $CUDA_VISIBLE_DEVICES
      - name: Clone TeraChem repo
        run: git clone https://imd-mtz:${{ secrets.IMD_MTZ_PAT }}@github.com/mtzgroup/terachem.git terachem
      - name: Configure TeraChem
        run: |
          cd terachem
          HOSTNAME=fire-fake ./configure
          cd ..
      - name: Compile TeraChem
        run: |
          cd terachem
          make -j16
          cd ..
  run-test-suite:
    runs-on: [self-hosted, 1gpu]
    needs: build-terachem
    container:
      image: vwcruzeiro/terachem_environment:latest
      env:
        CUDA_VISIBLE_DEVICES: ${{ env.CUDA_VISIBLE_DEVICES }}
    steps:
      - name: Name of the runner executing this job 
        run: echo ${{ runner.name }}
      - name: Print CUDA_VISIBLE_DEVICES, as seen inside the Docker container
        run: echo $CUDA_VISIBLE_DEVICES
      - name: Run TCPB-cpp tests
        run: |
          source terachem/build/terachem.sh
          export LD_LIBRARY_PATH=$(pwd)/lib:$LD_LIBRARY_PATH
          export PYTHONPATH=$(pwd)/pytcpb/build/lib:$PYTHONPATH
          cd terachem/tests
          python test.py -c TCPB-cpp -g 0 -l 0
          cd ../..
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            terachem/tests/run.log
            terachem/tests/summary.out
            terachem/tests/summary.err
          if-no-files-found: error
